name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update 
      run: rustup update nightly && rustup default nightly
    - name: Build io
      run: cargo build --verbose --lib -p gizmo-io --features tracing
